"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-27 01:01:15.582125
"""
from alembic import op

from app import ddl
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('opening_balance_minor', sa.Integer(), nullable=False),
    sa.Column('settlement_basis', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('flow', sa.String(length=10), nullable=False),
    sa.Column('grp', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_category_household_name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_household_id'), ['household_id'], unique=False)

    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('share_weight', sa.Integer(), nullable=False),
    sa.CheckConstraint('share_weight > 0', name='ck_member_share_weight_positive'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'name', name='uq_member_household_name')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_household_id'), ['household_id'], unique=False)

    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(is_default = 1 AND year IS NULL AND month IS NULL) OR (is_default = 0 AND year IS NOT NULL AND month IS NOT NULL)', name='ck_budget_default_shape'),
    sa.CheckConstraint('month IS NULL OR (month BETWEEN 1 AND 12)', name='ck_budget_month_range'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_household_id'), ['household_id'], unique=False)

    op.create_table('calendar_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_entry_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entry_household_id'), ['household_id'], unique=False)

    op.create_table('recurring_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('day_of_period', sa.Integer(), nullable=False),
    sa.Column('anchor_month', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('split_template', sa.String(length=10), nullable=False),
    sa.Column('split_member_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount_minor <> 0', name='ck_rule_amount_nonzero'),
    sa.CheckConstraint('day_of_period BETWEEN 1 AND 31', name='ck_rule_day_range'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['split_member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_rule_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rule_household_id'), ['household_id'], unique=False)

    op.create_table('savings_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_amount_minor', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('target_amount_minor > 0', name='ck_goal_target_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_goal_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_savings_goal_household_id'), ['household_id'], unique=False)

    op.create_table('recurring_rule_split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_minor <> 0', name='ck_rule_split_amount_nonzero'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['recurring_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'member_id', name='uq_rule_split_member')
    )
    with op.batch_alter_table('recurring_rule_split', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_rule_split_rule_id'), ['rule_id'], unique=False)

    op.create_table('recurring_skip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['recurring_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'occurrence_date', name='uq_skip_rule_date')
    )
    with op.batch_alter_table('recurring_skip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_skip_rule_id'), ['rule_id'], unique=False)

    op.create_table('txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recurring_rule_id', sa.Integer(), nullable=True),
    sa.Column('recurring_occurrence_date', sa.Date(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('txn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_txn_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_txn_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_txn_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_txn_recurring_rule_id'), ['recurring_rule_id'], unique=False)

    op.create_table('txn_split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount_minor <> 0', name='ck_split_amount_nonzero'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['txn_id'], ['txn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_id', 'member_id', name='uq_split_txn_member')
    )
    with op.batch_alter_table('txn_split', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_txn_split_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_txn_split_txn_id'), ['txn_id'], unique=False)

    ddl.install(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    ddl.uninstall(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('txn_split', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_txn_split_txn_id'))
        batch_op.drop_index(batch_op.f('ix_txn_split_member_id'))

    op.drop_table('txn_split')
    with op.batch_alter_table('txn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_txn_recurring_rule_id'))
        batch_op.drop_index(batch_op.f('ix_txn_household_id'))
        batch_op.drop_index(batch_op.f('ix_txn_date'))
        batch_op.drop_index(batch_op.f('ix_txn_category_id'))

    op.drop_table('txn')
    with op.batch_alter_table('recurring_skip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_skip_rule_id'))

    op.drop_table('recurring_skip')
    with op.batch_alter_table('recurring_rule_split', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_rule_split_rule_id'))

    op.drop_table('recurring_rule_split')
    with op.batch_alter_table('savings_goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_goal_household_id'))
        batch_op.drop_index(batch_op.f('ix_savings_goal_category_id'))

    op.drop_table('savings_goal')
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_rule_household_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_rule_category_id'))

    op.drop_table('recurring_rule')
    with op.batch_alter_table('calendar_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_entry_household_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_entry_date'))

    op.drop_table('calendar_entry')
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_household_id'))
        batch_op.drop_index(batch_op.f('ix_budget_category_id'))

    op.drop_table('budget')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_household_id'))

    op.drop_table('member')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_household_id'))

    op.drop_table('category')
    op.drop_table('household')
    # ### end Alembic commands ###
